server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}/${PAYSHEET_DB}paysheet
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: Paysheet

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka




