server:
  port: 8084

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: User
          uri: lb://User
          predicates:
            - Path=/users/**

        - id: Employee
          uri: lb://Employee
          predicates:
            - Path=/employees/**

        - id: Paysheet
          uri: lb://Paysheet
          predicates:
            - Path=/paysheets/**

